### ISSUE TITLE
Sandstone is uncraftable (reminder for later)

### ISSUE THREAD

**Issue by iownall555** [Minefix/MineFix#59]
Due to the sandstone to sandstone_normal name change, anything involving regular sandstone is rendered uncraftable.

*I'll fix this later, this is just so I don't forget.*

**Comment by iownall555** [comment]
Closing as this is fixed in PR #60

**Comment by PureTryOut** [comment]
For next time, if you mention "fixes #59" or something along those lines in the description of the PR, the issue will automatically get closed once the PR is merged. Also, since the PR isn't yet merged at the time of writing this it shouldn't have been closed yet ;)
